/**
 * Created by gukong on 2017/6/19.
 */

/**
 * 想看一看每个选项的效果
 * 访问这个网址 https://daneden.github.io/animate.css
 */
export const AnimationType = {
    BOUNCEIN: 'bounceIn',
    BOUNCEINDOWN: 'bounceInDown',
    BOUNCEINLEFT: 'bounceInLeft',
    BOUNCEINRIGHT: 'bounceInRight',
    BOUNCEINUP: 'bounceInUp',
    BOUNCEOUT: 'bounceOut',
    BOUNCEOUTDOWN: 'bounceOutDown',
    BOUNCEOUTLEFT: 'bounceOutLeft',
    BOUNCEOUTRIGHT: 'bounceOutRight',
    BOUNCEOUTUP: 'bounceOutUp',
    FADEIN: 'fadeIn',
    FADEINDOWN: 'fadeInDown',
    FADEINDOWNBIG: 'fadeInDownBig',
    FADEINLEFT: 'fadeInLeft',
    FADEINLEFTBIG: 'fadeInLeftBig',
    FADEINRIGHT: 'fadeInRight',
    FADEINRIGHTBIG: 'fadeInRightBig',
    FADEINUP: 'fadeInUp',
    FADEINUPBIG: 'fadeInUpBig',
    FADEOUT: 'fadeOut',
    FADEOUTDOWN: 'fadeOutDown',
    FADEOUTDOWNBIG: 'fadeOutDownBig',
    FADEOUTLEFT: 'fadeOutLeft',
    FADEOUTLEFTBIG: 'fadeOutLeftBig',
    FADEOUTRIGHT: 'fadeOutRight',
    FADEOUTRIGHTBIG: 'fadeOutRightBig',
    FADEOUTUP: 'fadeOutUp',
    FADEOUTUPBIG: 'fadeOutUpBig',
    FLIPINX: 'flipInX',
    FLIPINY: 'flipInY',
    FLIPOUTX: 'flipOutX',
    FLIPOUTY: 'flipOutY',
    LIGHTSPEEDIN: 'lightSpeedIn',
    LIGHTSPEEDOUT: 'lightSpeedOut',
    ROTATEIN: 'rotateIn',
    ROTATEINDOWNLEFT: 'rotateInDownLeft',
    ROTATEINDOWNRIGHT: 'rotateInDownRight',
    ROTATEINUPLEFT: 'rotateInUpLeft',
    ROTATEINUPRIGHT: 'rotateInUpRight',
    ROTATEOUT: 'rotateOut',
    ROTATEOUTDOWNLEFT: 'rotateOutDownLeft',
    ROTATEOUTDOWNRIGHT: 'rotateOutDownRight',
    ROTATEOUTUPLEFT: 'rotateOutUpLeft',
    ROTATEOUTUPRIGHT: 'rotateOutUpRight',
    JACKINTHEBOX: 'jackInTheBox',
    ROLLIN: 'rollIn',
    ROLLOUT: 'rollOut',
    ZOOMIN: 'zoomIn',
    ZOOMINDOWN: 'zoomInDown',
    ZOOMINLEFT: 'zoomInLeft',
    ZOOMINRIGHT: 'zoomInRight',
    ZOOMINUP: 'zoomInUp',
    ZOOMOUT: 'zoomOut',
    ZOOMOUTDOWN: 'zoomOutDown',
    ZOOMOUTLEFT: 'zoomOutLeft',
    ZOOMOUTRIGHT: 'zoomOutRight',
    ZOOMOUTUP: 'zoomOutUp',
    SLIDEINDOWN: 'slideInDown',
    SLIDEINLEFT: 'slideInLeft',
    SLIDEINRIGHT: 'slideInRight',
    SLIDEINUP: 'slideInUp',
    SLIDEOUTDOWN: 'slideOutDown',
    SLIDEOUTLEFT: 'slideOutLeft',
    SLIDEOUTRIGHT: 'slideOutRight',
    SLIDEOUTUP: 'slideOutUp',
}

export default AnimationType;